// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createCustomerStmt, err = db.PrepareContext(ctx, createCustomer); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCustomer: %w", err)
	}
	if q.deleteCustomerByIDStmt, err = db.PrepareContext(ctx, deleteCustomerByID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCustomerByID: %w", err)
	}
	if q.listCustomerByIDStmt, err = db.PrepareContext(ctx, listCustomerByID); err != nil {
		return nil, fmt.Errorf("error preparing query ListCustomerByID: %w", err)
	}
	if q.listCustomersStmt, err = db.PrepareContext(ctx, listCustomers); err != nil {
		return nil, fmt.Errorf("error preparing query ListCustomers: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createCustomerStmt != nil {
		if cerr := q.createCustomerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCustomerStmt: %w", cerr)
		}
	}
	if q.deleteCustomerByIDStmt != nil {
		if cerr := q.deleteCustomerByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCustomerByIDStmt: %w", cerr)
		}
	}
	if q.listCustomerByIDStmt != nil {
		if cerr := q.listCustomerByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCustomerByIDStmt: %w", cerr)
		}
	}
	if q.listCustomersStmt != nil {
		if cerr := q.listCustomersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCustomersStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                     DBTX
	tx                     *sql.Tx
	createCustomerStmt     *sql.Stmt
	deleteCustomerByIDStmt *sql.Stmt
	listCustomerByIDStmt   *sql.Stmt
	listCustomersStmt      *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                     tx,
		tx:                     tx,
		createCustomerStmt:     q.createCustomerStmt,
		deleteCustomerByIDStmt: q.deleteCustomerByIDStmt,
		listCustomerByIDStmt:   q.listCustomerByIDStmt,
		listCustomersStmt:      q.listCustomersStmt,
	}
}
