definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.Customers:
    properties:
      address:
        type: string
      city:
        type: string
      country:
        type: string
      createdAt:
        type: string
      customer_email:
        type: string
      customer_id:
        type: string
      customer_name:
        type: string
      customer_phone:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      is_active:
        type: boolean
      pincode:
        type: integer
      state:
        type: string
      tenant_id:
        type: string
      updatedAt:
        type: string
    required:
    - customer_email
    - customer_id
    - customer_name
    - customer_phone
    - is_active
    - tenant_id
    type: object
info:
  contact:
    email: support@swagger.io
    url: http://www.swagger.io/support
  description: Testing Swagger APIs.
  termsOfService: http://swagger.io/terms/// @contact.name API Support
  title: SalesService APIs
  version: "1.0"
paths:
  /customer:
    post:
      consumes:
      - application/json
      description: Create a Customer for an org.
      parameters:
      - description: Customer Data
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/models.Customers'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Customers'
      security:
      - Bearer: []
      summary: Create a Customer
      tags:
      - Customer
  /customer/{customer_id}:
    get:
      consumes:
      - application/json
      description: Retreive a customer by ID for an org.
      parameters:
      - description: CustomerID
        in: path
        name: customer_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Customers'
      security:
      - Bearer: []
      summary: Get Customer
      tags:
      - Customer
  /customers:
    get:
      consumes:
      - application/json
      description: Retreive all the customers for an org.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Customers'
      security:
      - Bearer: []
      summary: Get Customers
      tags:
      - Customer
schemes:
- http
- https
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
